version: '3'
services:
  db:
    build: docker/mysql5.7
    image: cakephp_sample_db
    container_name: cakephp_sample_db
    ports:
      - 3306:3306
  web:
    build: docker/apache_php5.6
    image: cakephp_sample_web
    container_name: cakephp_sample_web
    ports:
    - 8080:80
    volumes:
    - .:/var/www/app
    depends_on:
    - db
  php_cli:
    build: docker/php5.6
    image: cakephp_sample_php_cli
    volumes:
    - .:/var/www/app
    working_dir: /var/www/app
